package org.usfirst.frc3668.DeepSpace;

import org.usfirst.frc3668.DeepSpace.subsystems.subCargo;
import org.usfirst.frc3668.DeepSpace.subsystems.subChassis;
import org.usfirst.frc3668.DeepSpace.subsystems.subHatch;
import org.usfirst.frc3668.DeepSpace.subsystems.subLift;

import org.usfirst.frc3668.DeepSpace.commands.cmdGroupAutoTemplate;

import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableEntry;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.wpilibj.TimedRobot;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the TimedRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the build.properties file in the
 * project.
 */
public class Robot extends TimedRobot {

    static Command autonomousCommand;

    static SendableChooser<Settings.startLocation> startChooser = new SendableChooser<>();
    static SendableChooser<Settings.gameElementType> startGameChooser = new SendableChooser<>();
    static SendableChooser<Settings.locations> firstLocChooser = new SendableChooser<>();
    static SendableChooser<Settings.gameElementType> secondGameTypeChooser = new SendableChooser<>();
    static SendableChooser<Settings.locations> secondLocChooser = new SendableChooser<>();

    public static OI oi;
    public static subChassis subChassis;
    public static subLift subLift;
    public static subCargo subCargo;
    public static subHatch subHatch;
    public static RobotMap RobotMap;
    public static boolean isDriveInverted = true;

    public static NetworkTableInstance inst = NetworkTableInstance.getDefault();
	public static NetworkTable table = inst.getTable("limelight");
	public static NetworkTableEntry tx = table.getEntry("tx");
	public static NetworkTableEntry ty = table.getEntry("ty");
	public static NetworkTableEntry ta = table.getEntry("ta");
	public static NetworkTableEntry tv = table.getEntry("tv");
	public static NetworkTableEntry ts = table.getEntry("ts");
	public static NetworkTableEntry tl = table.getEntry("tl");
	
	public static NetworkTableEntry blink = table.getEntry("3");
	public static NetworkTableEntry on = table.getEntry("0");
	public static NetworkTableEntry Off = table.getEntry("1");

    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    @Override
    public void robotInit() {
        RobotMap = new RobotMap();
        RobotMap.init();
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        subChassis = new subChassis();
        subLift = new subLift();
        subCargo = new subCargo();
        subHatch = new subHatch();

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // OI must be constructed after subsystems. If the OI creates Commands
        //(which it very likely will), subsystems are not guaranteed to be
        // constructed yet. Thus, their requires() statements may grab null
        // pointers. Bad news. Don't move it.
        oi = new OI();

        startChooser.addOption("Center", Settings.startLocation.center);
        startChooser.addOption("Left", Settings.startLocation.left);
        startChooser.addOption("Right", Settings.startLocation.right);

        startGameChooser.addOption("Hatch", Settings.gameElementType.hatch);
        startGameChooser.addOption("Cargo", Settings.gameElementType.cargo);

        firstLocChooser.addOption("CS Center Left", Settings.locations.CSCL);
        firstLocChooser.addOption("CS Center Right", Settings.locations.CSCR);

        secondGameTypeChooser.addOption("Hatch", Settings.gameElementType.hatch);
        secondGameTypeChooser.addOption("Cargo", Settings.gameElementType.cargo);

        secondLocChooser.addOption("CS Center Left", Settings.locations.CSCL);
        secondLocChooser.addOption("CS Center Right", Settings.locations.CSCR);

        SmartDashboard.putData("Start Location", startChooser);
        SmartDashboard.putData("Start Game Type", startGameChooser);
        SmartDashboard.putData("First Destentation", firstLocChooser);
        SmartDashboard.putData("Second Game Type", secondGameTypeChooser);
        SmartDashboard.putData("Second Location", secondLocChooser);
    }

    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    @Override
    public void disabledInit(){

    }

    @Override
    public void disabledPeriodic() {
        Scheduler.getInstance().run();
    }

    @Override
    public void autonomousInit() {
        Settings.startLocation startLoc = startChooser.getSelected();
        Settings.gameElementType startGameType = startGameChooser.getSelected();
        Settings.locations firstLoc = firstLocChooser.getSelected();
        Settings.gameElementType secondGameType = secondGameTypeChooser.getSelected();
        Settings.locations secondLoc = secondLocChooser.getSelected();

        String [] parameters = new String [3];
        parameters[0] = Settings.filePerfix;
        parameters[1] = Settings.filePerfix;
        parameters[2] = Settings.filePerfix;

        switch (startLoc) {
            case center :
            parameters[0] = parameters[0] + Settings.startCenter;
                break;
            case left :
                parameters[0] = parameters[0] + Settings.startLeft;
                break;
            case right :
                parameters[0] = parameters[0] + Settings.startRight;
                break;
        }

        switch (firstLoc){
            case CSCL :
                parameters[0] = parameters[0] + Settings.cargoCenterLeft;
                parameters[1] = parameters[1] + Settings.cargoCenterLeft;
                break;
            case CSCR :
                parameters[0] = parameters[0] + Settings.cargoCenterRight;
                parameters[1] = parameters[1] + Settings.cargoCenterRight;
                break;
        }

        switch (secondGameType){
            case hatch :
                if(firstLoc == Settings.locations.CSCL){
                    parameters[1] = parameters[1] + Settings.loadStationLeft;
                } else if (firstLoc == Settings.locations.CSCR) {
                    parameters[1] = parameters[1] + Settings.loadStationRight;
                }
                break;
            case cargo :
                if(firstLoc == Settings.locations.CSCL){
                    parameters[1] = parameters[1] + Settings.depotCargoLeft;
                } else if (firstLoc == Settings.locations.CSCR) {
                    parameters[1] = parameters[1] + Settings.depotCargoRight;
                }
                break;
        }

        parameters[0] = parameters[0] + Settings.fileExt;
        parameters[1] = parameters[1] + Settings.fileExt;
        parameters[2] = parameters[2] + Settings.fileExt;

        Settings.actions[] actions = new Settings.actions[1];
        actions[0] = Settings.actions.placeHatch;
        
        autonomousCommand = new cmdGroupAutoTemplate(actions, parameters);
        
        if (autonomousCommand != null) autonomousCommand.start();
    }

    /**
     * This function is called periodically during autonomous
     */
    @Override
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
    }

    @Override
    public void teleopInit() {
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to
        // continue until interrupted by another command, remove
        // this line or comment it out.
        if (autonomousCommand != null) autonomousCommand.cancel();
    }

    /**
     * This function is called periodically during operator control
     */
    @Override
    public void teleopPeriodic() {
        SmartDashboard.putNumber("tx", tx.getDouble(0));
        SmartDashboard.putNumber("ty", ty.getDouble(0));
        Scheduler.getInstance().run();
    }
}
